<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="videoGen" nsURI="http://www.irisa.org/diverse/videogen" nsPrefix="videoGen">
  <eAnnotations source="http://www.eclipse.org/OCL/Import">
    <details key="ecore" value="http://www.eclipse.org/emf/2002/Ecore"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="invocationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="settingDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
    <details key="validationDelegates" value="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="Mandatory" eSuperTypes="#//Sequence"/>
  <eClassifiers xsi:type="ecore:EClass" name="Initialize" eSuperTypes="#//Transition"/>
  <eClassifiers xsi:type="ecore:EClass" name="VideoGen" eSuperTypes="#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="minMaxNotEqual"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="minMaxNotEqual" value="&#xA;&#x9;&#x9;&#x9;self.minDurationConstraint &lt;= self.maxDurationConstraint"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minDurationConstraint"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxDurationConstraint"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variantes" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transitions" lowerBound="1"
        upperBound="-1" eType="#//Transition" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="videos" lowerBound="1"
        upperBound="-1" eType="#//Video" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="minUserConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxUserConstraint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transition" abstract="true" interface="true"
      eSuperTypes="#//NamedElement">
    <eOperations name="execute" lowerBound="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextTransition" eType="#//Transition"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="active" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"
        defaultValueLiteral="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Optional" eSuperTypes="#//Sequence">
    <eAnnotations source="http://www.obeo.fr/dsl/dnc/archetype">
      <details key="archetype" value="Description"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="probMax probMin"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="probMax" value="&#xA;&#x9;&#x9;&#x9;self.probability &lt;= 100"/>
      <details key="probMin" value="&#xA;&#x9;&#x9;&#x9;self.probability >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Video" eSuperTypes="#//NamedElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimetype" lowerBound="1"
        eType="#//Mimetypes_Enum"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mimetypes_Enum">
    <eLiterals name="none"/>
    <eLiterals name="mp4" value="1"/>
    <eLiterals name="flv" value="2"/>
    <eLiterals name="mpegts" value="3"/>
    <eLiterals name="mpeg" value="4"/>
    <eLiterals name="webm" value="5"/>
    <eLiterals name="wmv" value="6"/>
    <eLiterals name="avi" value="7"/>
    <eLiterals name="mov" value="8" literal="mov"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alternatives" eSuperTypes="#//Sequence">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="probSumMax"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="probSumMax" value="&#xA;&#x9;&#x9;&#x9;self.options.probability->sum() &lt;= 100"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" lowerBound="2"
        upperBound="-1" eType="#//Optional" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generate" eSuperTypes="#//Transition"/>
  <eClassifiers xsi:type="ecore:EClass" name="Delay" eSuperTypes="#//Transition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="positiveDelay"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="positiveDelay" value="&#xA;&#x9;&#x9;&#x9;self.value >= 0"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" abstract="true" eSuperTypes="#//Transition">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="notIdentical"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore/OCL/Pivot">
      <details key="notIdentical" value="&#xA;&#x9;&#x9;&#x9;self.allInstances()->forAll(s1, s2 |&#xA;&#x9;&#x9;&#x9;&#x9;s1 &lt;> s2 implies s1.oclAsType(NamedElement).name &lt;> s2.oclAsType(NamedElement).name)"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="video" lowerBound="1" eType="#//Video"/>
  </eClassifiers>
</ecore:EPackage>
