/*
 * generated by Xtext
 */
package org.istic.idm.xtext.videogen;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class VideoGenUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.istic.idm.xtext.videogen.ui.internal.VideoGenActivator.getInstance().getInjector("org.istic.idm.xtext.videogen.VideoGen");
	}
	
}
