<?xml version="1.0" encoding="ASCII"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="videoGen" nsURI="http://videogenlmt/" nsPrefix="videoGen">
  <eClassifiers xsi:type="ecore:EClass" name="VideoGen" eSuperTypes="//NamedElement">
    <eOperations name="initialize">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eOperations name="compute">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sequences" upperBound="-1" eType="//Sequence" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selectedSequences" lowerBound="1" transient="true">
      <eGenericType>
        <eTypeArguments/>
        <eClassifier xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EEList"/>
      </eGenericType>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Sequence" abstract="true" interface="true" eSuperTypes="//NamedElement">
    <eOperations name="process">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="nextSibling" eType="//Sequence"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="current">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Alternatives" eSuperTypes="//Sequence">
    <eOperations name="checkProbabilities">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EMap"/>
    </eOperations>
    <eOperations name="process">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="options" upperBound="-1" eType="//Optional" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mandatory" eSuperTypes="//Sequence">
    <eOperations name="process">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="video" eType="//Video"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Optional" eSuperTypes="//Sequence">
    <eOperations name="process">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" lowerBound="1" defaultValueLiteral="0">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="video" eType="//Video"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Video" eSuperTypes="//NamedElement">
    <eOperations name="select">
      <eAnnotations source="aspect"/>
    </eOperations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="url" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="duration" lowerBound="1" defaultValueLiteral="0">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EIntegerObject"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mimetype" lowerBound="1" eType="//Mimetypes_Enum"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selected" lowerBound="1" defaultValueLiteral="false">
      <eAnnotations source="aspect"/>
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EBooleanObject"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Mimetypes_Enum">
    <eLiterals name="none" literal="NONE"/>
    <eLiterals name="mp4" value="1" literal="MP4"/>
    <eLiterals name="flv" value="2" literal="FLV"/>
    <eLiterals name="mpegts" value="3" literal="MPEGTS"/>
    <eLiterals name="mpeg" value="4" literal="MPEG"/>
    <eLiterals name="webm" value="5" literal="WEBM"/>
    <eLiterals name="wmv" value="6" literal="WMV"/>
    <eLiterals name="avi" value="7" literal="AVI"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="NamedElement" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1">
      <eType xsi:type="ecore:EDataType" href="http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
